version: "3.8"
services:
  #MySQL Service
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: financeular
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PORT: 3306
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    ports:
      - "1000:80"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db

  front:
    build:
      context: ./front
    ports:
      - "80:80"
    depends_on:
      - backend
