name: Tests
on: [push]

jobs:
  phpunit:
    name: Backend - Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cd in to the backend and run tests
        run: |
          cd backend
          composer install
          php artisan test
