name: Tests
on: [push]

jobs:
  phpunit:
    name: Backend - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - name: cd in to the backend and run linter
        run: |
          cd backend
          composer install
          composer run lint
