name: E2E
on: [push]

jobs:
  build:
    name: E2E

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Spinning up the container
        run: |
          docker-compose up -d

          sleep 20
          docker-compose exec -T backend php artisan financeular:user-create --email=john@testing.com --password=1234 --name=John
          docker-compose exec -T backend php artisan financeular:user-create --email=tom@testing.com --password=1234 --name=Tom

      - name: Install the cypress and trigger tests.
        run: |
          cd cypress
          npm i
          npm run test:headless

      - name: Upload Cypress Screenshots and Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |-
            /home/runner/work/financeular/financeular/cypress/cypress/screenshots
            /home/runner/work/financeular/financeular/cypress/cypress/videos
        if: ${{ failure() }}
